development:
  adapter: postgresql
  database: habits_bro_development
  encoding: unicode
  user: habits_bro
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: habits_bro_test
  encoding: unicode
  user: habits_bro
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: habits_bro_production
  encoding: unicode
  pool: 5
  timeout: 5000